import { eLayoutType, RoutesService } from '@abp/ng.core';
import { APP_INITIALIZER } from '@angular/core';

export const APP_ROUTE_PROVIDER = [
  { provide: APP_INITIALIZER, useFactory: configureRoutes, deps: [RoutesService], multi: true },
];

function configureRoutes(routes: RoutesService) {
  return () => {
    routes.add([
      {
        path: '/',
        name: '::Menu:Home',
        iconClass: 'fas fa-home',
        order: 1,
        layout: eLayoutType.application,
      },
      {
        path: '/pos',
        name: '::Menu:Pos',
        iconClass: 'fas fa-cart-plus',
        layout: eLayoutType.application,
        order: 2,
        requiredPolicy: 'ClientPortal.Orders',
      },
      {
        path: '/order-control-list',
        name: '::Menu:OrderControl',
        iconClass: 'fa fa-shopping-bag',
        layout: eLayoutType.application,
        order: 3,
        requiredPolicy: 'ClientPortal.Orders',
      },
      {
        path: '/payroll',
        name: '::Menu:Payroll',
        iconClass: 'fas fa-clock',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Payrolls',
      },
      {
        path: '/customers',
        name: '::Menu:Customer',
        iconClass: 'fas fa-user',
        order: 8,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Customers.View',
      },
      {
        path: '/products',
        name: '::Menu:Products',
        iconClass: 'fas fa-fan',
        order: 9,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Products',
      },
      {
        path: '/discounts',
        name: '::Menu:Discounts',
        iconClass: 'fas fa-tag',
        order: 13,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Discounts',
      },
      {
        path: '/giftCards',
        name: '::Menu:GiftCard',
        iconClass: 'fas fa-gifts',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.GiftCards',
      },

      {
        path: '/employees',
        name: '::Menu:Employees',
        iconClass: 'fas fa-users',
        layout: eLayoutType.application,
        order: 11,
        requiredPolicy: 'ClientPortal.Employees',
      },
      {
        name: '::Menu:Settings',
        iconClass: 'fas fa-cogs',
        order: 14,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Settings',
      },
      {
        name: '::Menu:ValueList',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-list-alt',
        order: 11,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Values',
      },
      {
        path: '/valuetypes',
        name: '::Menu:ValueTypeMapping',
        parentName: '::Menu:ValueList',
        iconClass: 'fas fa-list-alt',
        order: 12,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Values',
      },
      {
        path: '/valuetypesettings',
        name: '::Menu:ValueTypeSettings',
        parentName: '::Menu:ValueList',
        iconClass: 'fas fa-table',
        order: 13,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Values',
      },
      {
        path: '/corporateSettings',
        name: '::Menu:CorporateSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-users',
        order: 14,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.CorporateSettings',
      },
      {
        path: '/account-settings',
        name: '::Menu:AccountSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-user-cog',
        order: 15,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.AccountSettings',
      },
      {
        path: '/stores',
        name: '::Menu:Stores',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-store',
        order: 16,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Stores',
      },
      {
        path: '/employee-settings',
        name: '::Menu:EmployeeSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-users-cog',
        order: 17,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.EmployeeSettings',
      },
      {
        path: '/transaction-type-settings',
        name: '::Menu:TransactionTypeSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-truck',
        order: 7,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.PaymentTransactionCodes',
      },
      {
        path: '/shops',
        name: '::Menu:Shop',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-store-alt',
        order: 18,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Shops',
      },
      {
        name: '::Menu:Deliveries',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-truck',
        order: 19,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Deliveries',
      },
      {
        path: '/delivery-zones',
        name: '::Menu:DeliveryZones',
        iconClass: 'fas fa-map-marker-alt',
        parentName: '::Menu:Deliveries',
        order: 20,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryZones',
      },
      {
        path: '/deliveryModes',
        name: '::Menu:DeliveryModes',
        parentName: '::Menu:Deliveries',
        order: 22,
        iconClass: 'fas fa-bars',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryModes',
      },
      {
        path: '/calendar',
        name: '::Menu:Calendar',
        parentName: '::Menu:Deliveries',
        iconClass: 'fas fa-bars',
        order: 23,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryModeDateMap',
      },
      {
        path: '/delivery-code',
        name: '::Menu:DeliveryCode',
        iconClass: 'fas fa-barcode',
        parentName: '::Menu:Deliveries',
        order: 24,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryCodes',
      },
      {
        path: '/shipping-service',
        name: '::Menu:ShippingService',
        parentName: '::Menu:Deliveries',
        order: 25,
        iconClass: 'fas fa-shipping-fast',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.ShippingServices',
      },
      {
        path: '/delivery-charge-adjustment',
        parentName: '::Menu:Deliveries',
        name: '::Menu:DeliveryChargeAdjustmentSettings',
        iconClass: 'fas fa-chart-line',
        order: 26,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryChargeAdjustmentSettings',
      },
      {
        path: '/delivery-short-code',
        parentName: '::Menu:Deliveries',
        name: '::Menu:DeliveryShortCode',
        iconClass: 'fas fa-code',
        order: 27,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryShortCodes',
      },
      {
        path: '/deliveryMapOptionSettings',
        name: '::Menu:DeliveryMapOptionSettings',
        parentName: '::Menu:Deliveries',
        order: 28,
        iconClass: 'fas fa-cogs',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryMapOptionsSettings',
      },
      {
        path: '/vehicles',
        name: '::Menu:Vehicles',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-truck',
        order: 29,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Vehicles',
      },
      {
        path: '/messageShortcuts',
        name: '::Menu:MessageShortCut',
        parentName: '::Menu:Settings',
        iconClass: 'far fa-comment',
        order: 30,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.MessageShortcuts',
      },
      {
        path: '/credit-card-settings',
        name: '::Menu:CreditCardSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-cogs',
        order: 31,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.CreditCardSettings',
      },
      {
        path: '/sales-commissions',
        name: '::Menu:SalesCommission',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-wallet',
        order: 32,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Commissions',
      },
      {
        path: '/shops',
        name: '::Menu:Shop',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-store-alt',
        order: 33,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Shops',
      },
      {
        name: '::Menu:Messages',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-envelope',
        order: 34,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Messages',
      },
      {
        path: '/twilio-sms-settings',
        name: '::Menu:TwilioSmsSettings',
        parentName: '::Menu:Messages',
        iconClass: 'fas fa-comment-dots',
        order: 35,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.TwilioSmsSettings',
      },
      {
        path: '/smstemplates',
        name: '::Menu:SmsTemplates',
        parentName: '::Menu:Messages',
        iconClass: 'fas fa-sms',
        order: 36,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.SmsTemplates',
      },
      {
        path: '/sms-histories',
        name: '::Menu:SmsHistories',
        parentName: '::Menu:Messages',
        iconClass: 'fas fa-comments',
        order: 37,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.SmsHistories',
      },
      {
        name: '::Menu:Email',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-envelope',
        order: 38,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Email',
      },
      {
        path: '/tenant-email-settings',
        name: '::Menu:TenantEmailSettings',
        parentName: '::Menu:Email',
        iconClass: 'fas fa-envelope',
        order: 39,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.TenantEmailSettings',
      },
      {
        path: '/message-templates',
        name: '::Menu:MessageTemplates',
        parentName: '::Menu:Email',
        iconClass: 'fas fa-envelope',
        order: 40,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.MessageTemplates',
      },
      {
        path: '/queued-emails',
        name: '::Menu:QueuedEmails',
        parentName: '::Menu:Email',
        iconClass: 'fas fa-envelope',
        order: 41,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.QueuedEmails',
      },
      {
        path: '/logs',
        name: '::Menu:Logs',
        iconClass: 'fas fa-list',
        order: 15,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Logs.View',
      },
      {
        path: '/error-logs',
        name: '::Menu:ErrorLogs',
        iconClass: 'fas fa-list',
        order: 43,
        parentName: '::Menu:Logs',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Host',
      },
      {
        path: '/audit-logs',
        name: '::Menu:AuditLogs',
        iconClass: 'fas fa-list',
        order: 44,
        parentName: '::Menu:Logs',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Logs.View',
      },
      {
        path: '/scheduler-settings',
        name: '::Menu:SchedulerSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-table',
        order: 45,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.SchedulerSettings',
      },
      {
        path: '/wire-service-shops',
        name: '::Menu:WireServiceShop',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-store',
        order: 46,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.WireServiceShops',
      },
      {
        name: '::Menu:StoreSpecificSettings',
        parentName: '::Menu:Settings',
        iconClass: 'fas fa-store',
        order: 47,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.StoreSpecificSettings',
      },
      {
        path: '/store-credit-card-setup',
        name: '::Menu:StoreSpecificCreditCardSetup',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fas fa-credit-card',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.StoreSpecificCreditCardSetups',
      },
      {
        path: '/wire-service-setup',
        name: '::Menu:WireServiceSetup',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fab fa-servicestack',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.WireServiceSetup',
      },
      {
        path: '/store-wire-service-allocation',
        name: '::Menu:StoreSpecificWireServiceAllocation',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fas fa-network-wired',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.StoreSpecificWireServiceAllocationSettings',
      },
      {
        path: '/wire-service-message',
        name: '::Menu:WireServiceMessage',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fas fa-th-list',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.WireServiceMessage',
      },
      {
        path: '/card-design-setting',
        name: '::Menu:CardDesignSetting',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fas fa-palette',
        order: 6,
        layout: eLayoutType.application,
      },
      {
        name: '::Menu:AccountReceivable',
        iconClass: 'fas fa-cogs',
        order: 10,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.AccountReceivable',
      },
      {
        parentName: '::Menu:AccountReceivable',
        name: '::Menu:PaymentsAndAdjustments',
        iconClass: 'fas fa-chart-line',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.PaymentsAndAdjustments',
      },
      {
        path: '/terms-code-configuration',
        parentName: '::Menu:AccountReceivable',
        name: '::Menu:TermsCodeConfiguration',
        iconClass: 'fas fa-chart-line',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.TermsCode',
      },
      {
        path: '/batch-house-account-payment',
        parentName: '::Menu:PaymentsAndAdjustments',
        name: '::Menu:BatchHouseAccountPayment',
        iconClass: 'fas fa-chart-line',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.BatchDetails',
      },
      {
        path: '/individual-house-account-payment',
        parentName: '::Menu:PaymentsAndAdjustments',
        name: '::Menu:IndividualHouseAccountPayment',
        iconClass: 'fas fa-chart-line',
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.SinglePayment',
      },
      {
        name: '::Menu:DeliveryManagement',
        iconClass: 'fas fa-truck-moving',
        order: 6,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryManagement',
      },
      {
        path: '/deliveryManagement/delivery-control',
        name: '::Menu:DeliveryControl',
        parentName: '::Menu:DeliveryManagement',
        iconClass: 'fas fa-gamepad',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryControl',
      },
      {
        path: '/deliveryManagement/routing',
        name: '::Menu:Routing',
        parentName: '::Menu:DeliveryManagement',
        iconClass: 'fas fa-map',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryRoutes',
      },
      {
        path: '/deliveryManagement/driver-summary',
        name: '::Menu:DriverSummary',
        parentName: '::Menu:DeliveryManagement',
        iconClass: 'fas fa-clipboard',
        order: 3,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DeliveryManagement',
      },
      {
        path: '/invoice-report',
        name: '::Menu:Invoicing',
        iconClass: 'fas fa-file-invoice',
        order: 47,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.InvoiceReports',
      },
      {
        name: '::Menu:Reports',
        iconClass: 'fas fa-file',
        order: 48,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Reports',
      },
      {
        path: '/order-report',
        parentName: '::Menu:Reports',
        name: '::Menu:OrderReport',
        iconClass: 'fa fa-file-invoice',
        layout: eLayoutType.application,
        order: 1,
        requiredPolicy: 'ClientPortal.Reports.OrderRequirementsListReport',
      },
      {
        parentName: '::Menu:Reports',
        name: '::Menu:ProductSalesAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 2,
        requiredPolicy: 'ClientPortal.Reports.ProductSalesAnalysisReport',
      },
      {
        path: '/product-ranking-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:ProductRankingReport',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 1,
      },
      {
        path: '/customer-product-analysis-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:CustomerProductAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 2,
      },
      {
        path: '/store-sales-analysis-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:StoreSalesAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 3,
      },
      {
        path: '/sales-variance-by-sales-rep-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:SalesVarianceBySalesRep',
        iconClass: 'fa fa-chart-bar',
        layout: eLayoutType.application,
        order: 5,
      },
      {
        name: '::Menu:SalesComparisons',
        parentName: '::Menu:Reports',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 5,
        requiredPolicy: 'ClientPortal.Reports.SalesComparisonByDateRangeReport',
      },
      {
        name: '::Menu:CancellationCredit&ReplacementReport',
        parentName: '::Menu:Reports',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 6,
        requiredPolicy: 'ClientPortal.Reports.CancellationCreditAndReplacementsReport',
      },
      {
        path: '/business-analysis-report',
        name: '::Menu:BusinessAnalysisReport',
        parentName: '::Menu:Reports',
        iconClass: 'fa fa-chart-line',
        layout: eLayoutType.application,
        order: 7,
        requiredPolicy: 'ClientPortal.Reports.BusinessAnalysisReport',
      },
      {
        path: '/creditAndReplacementReport',
        name: '::Menu:Credit&ReplacementReport',
        parentName: '::Menu:CancellationCredit&ReplacementReport',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 1,
      },
      {
        path: '/cancelledOrdersReport',
        name: '::Menu:CancelledOrdersReport',
        parentName: '::Menu:CancellationCredit&ReplacementReport',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 2,
      },
      {
        path: '/product-sales-comparisons-report',
        name: '::Menu:ProductSalesComparisons',
        parentName: '::Menu:SalesComparisons',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 1,
      },
      {
        name: '::Menu:DriverActivity',
        parentName: '::Menu:DeliveryManagement',
        iconClass: 'fas fa-car',
        order: 49,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DriversActivity',
      },
      {
        path: '/driverActivities/driver-check-out',
        name: '::Menu:DriverCheckOut',
        parentName: '::Menu:DriverActivity',
        iconClass: 'fas fa-arrow-right',
        order: 1,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DriversActivity.CheckOut',
      },
      {
        path: '/driverActivities/driver-check-in',
        name: '::Menu:DriverCheckIn',
        parentName: '::Menu:DriverActivity',
        iconClass: 'fas fa-arrow-left',
        order: 2,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.DriversActivity.CheckIn',
      },
      {
        path: '/product-sales-by-order-placement-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:ProductSalesByOrderPlacement',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 5,
      },
      {
        path: '/product-type-comparisons-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:ProductTypeComparisons',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 4,
      },
      {
        path: '/customer-sale-performance-report',
        name: '::Menu:CustomerSalePerformance',
        parentName: '::Menu:ProductSalesAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 6,
      },
      {
        path: '/product-sales-comparisons-by-sales-person-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:ProductSalesComparisonsBySalesPerson',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 5,
      },
      {
        path: '/product-sales-comparison-by-customers-report',
        name: '::Menu:ProductSalesComparisonByCustomer',
        parentName: '::Menu:ProductSalesAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 4,
      },
      {
        path: '/product-sales-by-delivery-type-report',
        name: '::Menu:ProductSalesByDeliveryType',
        parentName: '::Menu:ProductSalesAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 7,
      },
      {
        path: '/salesman-gross-margin-analysis-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:SalesmanGrossMarginAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 4,
      },
      {
        path: '/product-sales-comparisons-by-occasion-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:ProductSalesComparisonsByOccasion',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 9,
      },
      {
        parentName: '::Menu:Reports',
        name: '::Menu:EmployeeProductivityReport',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 5,
        requiredPolicy: 'ClientPortal.Reports.EmployeeProductivityReport',
      },
      {
        path: '/sales-rep-productivity-detail-report',
        parentName: '::Menu:EmployeeProductivityReport',
        name: '::Menu:SalesRepProductivityDetail',
        iconClass: 'fa fa-scroll',
        layout: eLayoutType.application,
        order: 1,
      },
      {
        path: '/sales-rep-productivity-summary-report',
        parentName: '::Menu:EmployeeProductivityReport',
        name: '::Menu:SalesRepProductivitySummary',
        iconClass: 'fa fa-business-time',
        layout: eLayoutType.application,
        order: 2,
      },
      {
        path: '/time-card-summary-report',
        parentName: '::Menu:TimeClockReportingAndSummary',
        name: '::Menu:TimeCardSummary',
        iconClass: 'fa fa-clock',
        layout: eLayoutType.application,
        order: 3,
      },
      {
        path: '/payperiod-summary-report',
        parentName: '::Menu:TimeClockReportingAndSummary',
        name: '::Menu:PayPeriodSummary',
        iconClass: 'fa fa-calendar-check',
        layout: eLayoutType.application,
        order: 4,
      },
      {
        path: '/driver-summary',
        parentName: '::Menu:EmployeeProductivityReport',
        name: '::Menu:DriverSummaryReport',
        iconClass: 'fa fa-truck',
        layout: eLayoutType.application,
        order: 3,
      },
      {
        path: '/discount-granted-analysis-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:DiscountGrantedAnalysisReport',
        iconClass: 'fa fa-file-invoice-dollar',
        layout: eLayoutType.application,
        order: 6,
      },
      {
        path: '/salesman-gross-margin-analysis-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:SalesmanGrossMarginAnalysis',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 4,
      },
      {
        path: '/order-master-list-report',
        parentName: '::Menu:Reports',
        name: '::Menu:OrderMasterListReport',
        iconClass: 'fa fa-file-invoice',
        layout: eLayoutType.application,
        order: 2,
        requiredPolicy: 'ClientPortal.Reports.OrderMasterListReport',
      },

      {
        path: '/locked-orders',
        name: '::Menu:LockedOrder',
        iconClass: 'fas fa-lock',
        layout: eLayoutType.application,
        order: 17,
        requiredPolicy: 'ClientPortal.Orders.LockedOrder',
      },
      {
        path: '/misc-order-list',
        name: '::Menu:MiscOrder',
        iconClass: 'fas fa-boxes',
        order: 16,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Orders.MiscOrder',
      },
      {
        path: '/sales-analysis-by-sales-reps-report',
        parentName: '::Menu:ProductSalesAnalysis',
        name: '::Menu:SalesAnalysisBySalesReps',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 5,
      },
      {
        path: '/printer-setup',
        name: '::Menu:PrinterSetup',
        parentName: '::Menu:StoreSpecificSettings',
        iconClass: 'fas fa-print',
        order: 5,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.Printing',
      },
      {
        path: '/checkout-box',
        name: '::Menu:CheckoutBox',
        iconClass: 'fas fa-tasks',
        order: 4,
        layout: eLayoutType.application,
        requiredPolicy: 'ClientPortal.CheckoutBox',
      },
      {
        parentName: '::Menu:Reports',
        name: '::Menu:TimeClockReportingAndSummary',
        iconClass: 'fa fa-cube',
        layout: eLayoutType.application,
        order: 18,
        requiredPolicy: 'ClientPortal.Reports.TimeClockReportingAndSummaryReport',
      },
      {
        path: '/designer-order-list',
        name: '::Menu:DesignerOrderControl',
        iconClass: 'fa fa-scissors',
        layout: eLayoutType.application,
        order: 5,
        requiredPolicy: 'ClientPortal.Design',
      },
    ]);
  };
}
